# Generated by Django 4.2.7 on 2023-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='join_way',
            field=models.TextField(default='none', null=True),
        ),
    ]
