# Generated by Django 4.2.7 on 2023-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='fin_co_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
