# Generated by Django 4.2.7 on 2023-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propensity',
            name='deposit_type',
            field=models.CharField(default='미선택', max_length=10),
        ),
    ]
